services:
  backend:
    image: ${DESKTOP_PLUGIN_IMAGE}
    cap_add:
      - DAC_OVERRIDE
      - FOWNER
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
      - image-watcher-db:/var/image-watcher-db:rw
    # ports:
      # - "3111:3000"
volumes:
  image-watcher-db: {}
